//////////////////////////////////////////////////
// File autogenerated by buildcounter
// Do not hand edit! (preferably)
//////////////////////////////////////////////////

#ifndef BUILDID_MATERIALEDITOR_H
#define BUILDID_MATERIALEDITOR_H

const char* GetBuildID_MaterialEditor();


#endif //BUILDID_MATERIALEDITOR_H
